## today-money-web (dev)
##
## - Runs Next.js dev server on port 3000
## - Uses Node.js 24
## - Assumes Postgres runs in a separate container on the SAME docker network
##
# Use the official Node.js image
FROM arm64v8/node:20

# Create app directory
WORKDIR /usr/src/app

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Install app dependencies
# Copy the package.json AND package-lock.json if available
COPY package*.json ./

RUN npm ci

# Bundle app source
COPY . .

# Your app binds to port 3000
EXPOSE 3000

CMD [ "npm", "start" ]

